### ISSUE TITLE
We need a version bump

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#102]
As it says on the tin

Both Cargo.toml and crates.io say that mos6502 is at version 0.5.0, but whatever cargo pulls in with `cargo add mos6502` does not have `mos6502::instruction::Cmos6502`.

https://github.com/mre/mos6502/blob/265ef6941e0c988e50d8d2d3faef7c90a690d22e/Cargo.toml#L33

**Comment by mre** [comment]
Yup, good idea. Can you do it? I think/hope you should have the necessary permissions. If not, let me know and I can change that. :)

**Comment by omarandlorraine** [comment]
More than happy to do it. If I understand correctly, the way this happens is that if the version in Cargo.toml changes, a CI/CD run automagically publishes to crates.io when the PR merges. Is this correct?

**Comment by mre** [comment]
exactly!

**Comment by mre** [comment]
Minor correction: you also need to push a tag.
