### ISSUE TITLE
Add more Tests

### ISSUE THREAD

**Issue by senden9** [mre/mos6502#12]
Hi!

I think, now that we have automatic CI test runs, a few more test would be helpful. For that i suggest to let the emulator panic or return an error if we hit an unknown command. At the moment unknown commands are simply ignored. 

It is maybe a good idea to test against the [6502_functional_test.a65](https://github.com/Klaus2m5/6502_65C02_functional_tests/blob/fe99e5616243a1bdbceaf5907390ce4443de7db0/6502_functional_test.a65). What say the other people?

**Comment by mre** [comment]
Aye, that's a great idea! 
Maybe there's a way to auto-generate some tests from the resource (and others) that you mentioned. Do you want to tackle that one?

**Comment by senden9** [comment]
Also a good + funny idea. But I have not much spare time under the week. So will not _claim_ that now.

**Comment by mre** [comment]
We got quite a few more unit tests now, so I'll go ahead and close this.
The functional test is still untouched but I don't think we should keep that issue open any longer. Probably there are better ways to do it by now than my crude attempt in #17.
