### ISSUE TITLE
Add #[no_std] support.

### ISSUE THREAD

**Issue by thejpster** [mre/mos6502#3]
Would love to use this on Monotron.

**Comment by mre** [comment]
Very old ticket. Haven't cleaned up that repo in a long while.
Anyway, no_std support should work. If anyone wants to give it a shot, please do. 
We can reopen this issue in case we still run into issues or create a new one.
Pretty sure it's not on the roadmap for integration into Monotron (sadly), but if somebody
wants to try something similar I'd be delighted to hear about it. 
Thanks for giving me the inspiration to work on this crate in the first place @thejpster. ⭐
