### ISSUE TITLE
Outdated FIXME comment

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#37]
`src/registers.rs` has on line 154 the following comment
```
// JAM: FIXME: Should we prevent overflow here? What would a 6502 do?
```

The real 6502 will just ignore the stackpointer wrap-wround issue in a way that's consistent with the current implementation so there is no need for the FIXME comment.

**Comment by mre** [comment]
Thanks for the tip @omarandlorraine. Cleaned it up. 😃
