### ISSUE TITLE
The doctests don't pass

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#48]
When I run `cargo test` here on the master branch, I'm getting a failure in `readme_sect_how_to_use_this_library_line_22`

Do you know the reason?

**Comment by omarandlorraine** [comment]
Weird, the issue seemed to be local to my setup. `cargo clean` actually sorted it out for me.

**Comment by mre** [comment]
Huh, that's strange. Let's keep an eye on it. Thanks for the feedback.
