### ISSUE TITLE
We need to be able to represent the memory "better"

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#50]
Some machines like the Commodore 64 have a lot of bank switching, and memory map I/O, etc etc. There's way more addressable memory than just 64K, and this includes UARTs, the sound chip, etc etc.

Then things like the Atari 2600 which have 128 bytes of RAM only, and so the stack and zero page all overlap.

[From what I can see](https://github.com/mre/mos6502/blob/master/src/memory.rs#L57), currently this emulator implements memory as a flat array, so that precludes its use in an emulator of the above systems.

What we should do instead is define a trait that has the necessary functions for reading & writing to memory. This can then be `impl`ed by the host, and it can do what is right.

**Comment by omarandlorraine** [comment]
Yep, that's fine, I think that's a sensible default

**Comment by mre** [comment]
Speaking of which, I still don't know how to implement this.
Especially what to do in cases like that:
https://github.com/mre/mos6502/blob/f3d3bf470f10a0d3789472df6321f5aae2001b47/src/cpu.rs#L53-L55

We would need to reset the memory as well and the type of `Memory` would depend on what was passed in the constructor.

**Comment by omarandlorraine** [comment]
>We would need to reset the memory as well

Why do we need to so that? Memory doesn't have a reset pin like the CPU does

**Comment by omarandlorraine** [comment]
Also, why does CPU::reset() call CPU::new()?

It should do the same stack accesses as the real chip, and also leave most of the registers alone. An actual 6502 only initializes the stack pointer and the interrupt flag; maybe this emulator should do the same

**Comment by omarandlorraine** [comment]
Having a generic argument on CPU (i.e. `CPU<M>`) will also affect `AddressingMode::process`. The function signature will need to change. I want to suggest moving address calculations into the CPU instead of having the CPU's state leaking into `AddressingMode::process` function. What do you think? Can you see a better way?

**Comment by mre** [comment]
> Why do we need to so that? Memory doesn't have a reset pin like the CPU does

Oh, then we don't. I was confusing the (theoretically) correct handling of a memory reset with the practical implementation in hardware. Let's stay as close to the hardware as possible, yeah.

**Comment by mre** [comment]
>  An actual 6502 only initializes the stack pointer and the interrupt flag when it's reset; maybe this emulator should do the same.

Is this the correct behavior?
https://github.com/gianlucag/mos6502/blob/master/mos6502.cpp#L820-L835

I guess we can do something similar.

**Comment by mre** [comment]
> Having a generic argument on CPU (i.e. CPU<M>) will also affect AddressingMode::process. The function signature will need to change. I want to suggest moving address calculations into the CPU instead of having the CPU's state (in particular, the memory and registers X and Y) leaking into AddressingMode::process function. What do you think? Can you see a better way?

I don't have an opinion on this. So far I don't see a reason why we can't move the calculations into the CPU if that makes things easier. 👍

**Comment by mre** [comment]
I changed my mind about this part:

```rust
impl Default for CPU {
    fn default() -> Self {
        Self::new(Memory::default())
    }
}
```

We probably don't want to have a `Default` for `CPU` as there is no reasonable default for `Memory`: it depends on the hardware that is emulated. We should probably be explicit about it and require the user to set up the correct amount of memory.
