### ISSUE TITLE
Please impl Default for mos6502::cpu::CPU

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#51]
I'm rejigging my project to use use emulator but I'm running into this issue where the Default trait is not impl'd for mos6502::cpu::CPU.

I wanted to do this

```
impl Default for mos6502::cpu::CPU {
    fn default() -> Self {
        Self::new()
    }  
}
```

but it's not allowed because neither Default nor mos6502::cpu::CPU are from my crate

That said I don't really know what Default::default should do here. On the real chip, some of the registers are not preset to a value at reset.

What do we think?

**Comment by mre** [comment]
We discussed that in https://github.com/mre/mos6502/issues/50#issuecomment-1212099019. Would that work for you?

**Comment by omarandlorraine** [comment]
Oh yikes! I completely forgot about that. Apologies for the noise
