### ISSUE TITLE
No wrap-around for indexed addressing modes

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#52]
There are a few addressing modes that should look at zero page only, such as ZeroPageX, ZeroPageY, and IndexedIndirectX.

Real hardware would add the address and the index register, but wrap around so that the address is always within zero page. 

This emulator panics when the real hardware would wrap around. The locus of the bug is in `AddressingMode::process`, in `src/instruction.rs`, wherever the `+` symbol is found. So far as I can tell, this is on lines 196, 202, 236, and 247. Principally, the same issue affects also Indexed Absolute modes (see lines 217 and 222), though of course the nature of the wrap-around is different.

**Comment by omarandlorraine** [comment]
The same problem affects also the program counter, which may wrap around in these scenarios:

- the implicit increment after an instruction fetch
- the relative branching

I'm working on a fix, see the `addrfix` branch

**Comment by mre** [comment]
Yeah that makes a lot of sense. Thanks for working on a fix.
So you say instead of

```rust
OpInput::UseAddress(Address(u16::from(arr[0] + x)))
```

it should be

```rust
OpInput::UseAddress(Address(u16::from(arr[0]).wrapping_add(u16::from(x))))
```

Is that correct?

**Comment by omarandlorraine** [comment]
In most cases, yes, that is correct. There's one more fiddly edge case to take care of and that's when the wrap around happens between two consecutive reads, such as would happen if a pointer is read from addresses `0xff` and `0x00`. This is very similar in nature to the indirect jump bug on NMOS chips. The new addrfix branch makes no attempt at handling this (yet?) though
