### ISSUE TITLE
The emulator should panic when hitting an unimplemented opcode

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#55]
The 6502 has some undecoded opcodes, some of which crash the CPU. I think this should raise some kind of exception that client code can handle using a `catch_unwind` or something. 

For example, if a Commodore 64 emulator runs into this kind of opcode, I know VICE at least prompts the user if he wants to close the emulator, or reset the CPU, or cold start the machine. 

From what I understand, this emulator gets stuck in a never-ending loop.

What do you think? Should this emulator `panic!` when encountering an unknown opcode? Or perhaps return a `Result<(), Something>`?

**Comment by mre** [comment]
A common approach I saw in other emulators is the usage of [`unimplemented!`](https://doc.rust-lang.org/std/macro.unimplemented.html), which panics with a message and can be captured with a `catch_unwind`.

> From what I understand, this emulator gets stuck in a never-ending loop.

Oh, I thought it would just skip the instruction and move on?
The code for it is here: https://github.com/mre/mos6502/blob/11e48c1691db2b3ce97257137b8dabf952b4e3f7/src/cpu.rs#L410-L413

In any case we can change that to `unimplemented!` or something else that panics.
