### ISSUE TITLE
The RTS instruction is not emulated

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#66]
The massive `match` statement in `execute_instruction` ([here](https://github.com/mre/mos6502/blob/master/src/cpu.rs#L184)) does not include code to match and execute the `RTS` instruction.

This bug was discovered by [solid65](https://github.com/omarandlorraine/solid65/).

The RTS instruction takes six cycles, but only reads two bytes off the stack. Does anyone know how the remaining cycles are spent?

**Comment by mre** [comment]
I wonder if we could add an integration test / functional test based on solid65 to this repo. It would fail right now, but it would highlight if we are making progress. No rush, just mentioning it here.

**Comment by omarandlorraine** [comment]
I could probably get solid65 to output a test case if it discovers a discrepancy. Then, after a human has vetted the test case, it can be added to mos6502's CI/CD pipeline.

Does that seem like the kind of thing you're thinking about?

**Comment by mre** [comment]
Actually, I thought about running solid65 as a GitHub Action on every pull request. It would just try to run all tests and fail the pipeline if it fails. Right now, we don't have any end-to-end tests at all. 😅

**Comment by omarandlorraine** [comment]
It's an interesting thought. So far solid65 is a fuzztester run under human supervision. But if we could change that, we could have it run in a CI/CD pipeline

**Comment by mre** [comment]
Maybe it could also run https://github.com/Klaus2m5/6502_65C02_functional_tests for each emulator. It could grow into a general test suite.
