### ISSUE TITLE
New versions not on cargo.io

### ISSUE THREAD

**Issue by omarandlorraine** [mre/mos6502#70]
We have released versions 0.3.0 and 0.4.0, but crates.io seems stuck on version 0.2.0 from arodn 2 years ago.

**Comment by mre** [comment]
Huh, let me quickly push a new release. For the future, we should push it to crates.io automatically with Github actions.

**Comment by mre** [comment]
Alright, I published [0.3.0](https://crates.io/crates/mos6502/0.3.0) and [0.4.0](https://crates.io/crates/mos6502/0.4.0) and bumped `master` to 0.5.0 for the next release.

**Comment by mre** [comment]
Alright, we set up the pipeline, so this should no longer happen in the future. Now, whenever we tag a release, it will automatically be pushed to crates.io.

**Comment by omarandlorraine** [comment]
Thanks!
